-- V6: 规则状态从三态(DRAFT/PUBLISHED/STOPPED)改为双态(UNPUBLISHED/PUBLISHED)
-- 符合 PRD 双维度状态模型：发布状态(UNPUBLISHED/PUBLISHED) + 运行状态(NOT_RUN/HAS_RUN)

-- 将 DRAFT 和 STOPPED 统一改为 UNPUBLISHED
UPDATE tag_rule SET status = 'UNPUBLISHED' WHERE status IN ('DRAFT', 'STOPPED');

-- 修改默认值
ALTER TABLE tag_rule ALTER COLUMN status SET DEFAULT 'UNPUBLISHED';

-- 更新注释
COMMENT ON COLUMN tag_rule.status IS 'UNPUBLISHED / PUBLISHED';
